

services:
  backend:
    image: balacotes/whatai:backend
    container_name: whatsapp_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - chroma_data:/app/chroma_db
    environment:
      - CHROMA_DB_DIR=/app/chroma_db
      - DOCUMENTS_DIR=/app/documentos

  frontend:
    image: balacotes/whatai:frontend
    container_name: whatsapp_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  chroma_data:
